# Generated by Django 3.2.4 on 2021-06-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='external_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
