# Generated by Django 3.2.4 on 2021-06-18 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210618_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 13, 52, 55, 583141, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
